### ISSUE TITLE
Подключение приложения ломает миграции

### ISSUE THREAD

**Issue by mcd-php** [marazmiki/django-ulogin#31]
Таблица `django_ulogin_uloginuser` ссылается на `auth_user`, но создаётся ранее неё.

`stderr.txt`:
```
Traceback (most recent call last):
  File "/opt/my_cool_project/lib/python3.4/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
  File "/opt/my_cool_project/lib/python3.4/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/opt/my_cool_project/lib/python3.4/site-packages/MySQLdb/cursors.py", line 226, in execute
    self.errorhandler(self, exc, value)
  File "/opt/my_cool_project/lib/python3.4/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorvalue
  File "/opt/my_cool_project/lib/python3.4/site-packages/MySQLdb/cursors.py", line 217, in execute
    res = self._query(query)
  File "/opt/my_cool_project/lib/python3.4/site-packages/MySQLdb/cursors.py", line 378, in _query
    rowcount = self._do_query(q)
  File "/opt/my_cool_project/lib/python3.4/site-packages/MySQLdb/cursors.py", line 341, in _do_query
    db.query(q)
  File "/opt/my_cool_project/lib/python3.4/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
_mysql_exceptions.OperationalError: (1005, "Can't create table 'my_cool_project.#sql-bb5_6' (errno: 150)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/my_cool_project/lib/python3.4/site-packages/django/core/management/__init__.py", line 354, in execute_from_command_line
    utility.execute()
  File "/opt/my_cool_project/lib/python3.4/site-packages/django/core/management/__init__.py", line 346, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/my_cool_project/lib/python3.4/site-packages/django/core/management/base.py", line 394, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/my_cool_project/lib/python3.4/site-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/opt/my_cool_project/lib/python3.4/site-packages/django/core/management/commands/migrate.py", line 179, in handle
    created_models = self.sync_apps(connection, executor.loader.unmigrated_apps)
  File "/opt/my_cool_project/lib/python3.4/site-packages/django/core/management/commands/migrate.py", line 318, in sync_apps
    cursor.execute(statement)
  File "/opt/my_cool_project/lib/python3.4/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/opt/my_cool_project/lib/python3.4/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/opt/my_cool_project/lib/python3.4/site-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/opt/my_cool_project/lib/python3.4/site-packages/django/utils/six.py", line 658, in reraise
    raise value.with_traceback(tb)
  File "/opt/my_cool_project/lib/python3.4/site-packages/django/db/backends/utils.py", line 62, in execute
    return self.cursor.execute(sql)
  File "/opt/my_cool_project/lib/python3.4/site-packages/django/db/backends/mysql/base.py", line 124, in execute
    return self.cursor.execute(query, args)
  File "/opt/my_cool_project/lib/python3.4/site-packages/MySQLdb/cursors.py", line 226, in execute
    self.errorhandler(self, exc, value)
  File "/opt/my_cool_project/lib/python3.4/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorvalue
  File "/opt/my_cool_project/lib/python3.4/site-packages/MySQLdb/cursors.py", line 217, in execute
    res = self._query(query)
  File "/opt/my_cool_project/lib/python3.4/site-packages/MySQLdb/cursors.py", line 378, in _query
    rowcount = self._do_query(q)
  File "/opt/my_cool_project/lib/python3.4/site-packages/MySQLdb/cursors.py", line 341, in _do_query
    db.query(q)
  File "/opt/my_cool_project/lib/python3.4/site-packages/MySQLdb/connections.py", line 280, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1005, "Can't create table 'my_cool_project.#sql-bb5_6' (errno: 150)")
```

Журнал SQL запросов:
```
SET NAMES utf8
set autocommit=1
SET SQL_AUTO_IS_NULL = 0
SHOW FULL TABLES
CREATE TABLE `django_migrations` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `app` varchar(255) NOT NULL, `name` varchar(255) NOT NULL, `applied` datetime NOT NULL)
SELECT engine FROM information_schema.tables WHERE table_name = 'django_migrations'
SELECT `django_migrations`.`app`, `django_migrations`.`name` FROM `django_migrations`
SHOW FULL TABLES
set autocommit=0
CREATE TABLE `django_ulogin_uloginuser` (`id` integer AUTO_INCREMENT NOT NULL PRIMARY KEY, `user_id` integer NOT NULL, `network` varchar(255) NOT NULL, `identity` varchar(255) NOT NULL, `uid` varchar(255) NOT NULL, `date_created` datetime NOT NULL, UNIQUE (`network`, `uid`))
SELECT engine FROM information_schema.tables WHERE table_name = 'django_ulogin_uloginuser'
ALTER TABLE `django_ulogin_uloginuser` ADD CONSTRAINT `django_ulogin_uloginuse_user_id_4ad90afc4bd72726_fk_auth_user_id` FOREIGN KEY (`user_id`) REFERENCES `auth_user` (`id`)
rollback
set autocommit=1
```

P.S. Инструкция по установке битая, надо добавить `https://`, делать пулл-реквест в лом.
```diff
diff --git a/README.rst b/README.rst
index 2cce4be..644f578 100644
--- a/README.rst
+++ b/README.rst
@@ -66 +66 @@ Django-ulogin является приложением для социально
-    $ pip install -e git+github.com/marazmiki/django-ulogin.git#egg=django-ulogin
+    $ pip install -e git+https://github.com/marazmiki/django-ulogin.git#egg=django-ulogin

```

**Comment by marazmiki** [comment]
По поводу миграций: в пакете их нет вообще. Ни "родных" миграций django 1.7+, на старых от south. Поэтому они ничего ломать не могут :)

Думаю, Ваша проблема решается на уровне проекта. Именно  внутри него Вы можете или отказаться от миграций этого приложения, или же использовать свой модуль и носить их прямо там. См. документацию по параметру [MIGRATION_MODULES](https://docs.djangoproject.com/en/1.8/ref/settings/#std:setting-MIGRATION_MODULES)

За опечатку в инструкции спасибо, исправлю.

**Comment by mcd-php** [comment]
Если миграций нету - пожалуйста добавьте их, или скажите мне как добавить - взвести где-то одну опцию или сгенерить файлик через консоль Джанго ?

У меня есть опыт на Питоне, но только переработка данных, не сайты. На очередном проекте появилась необходимость тянуть в веб задачи для которых лучше подходят библиотеки имеющиеся в Питоне. 

Джанго поставил по туториалу, начал искать и прикручивать модули, обнаружил что если Ваш модуль раскомментировать в настройках то всё ломается, а если закомментировать - то `./manage.py migrate` отрабатывает нормально.

Пожалуйста укажите какие инструкции выполнить по шагам чтобы оно отрабатывало и с Вашим модулем тоже, патчи верну.

**Comment by marazmiki** [comment]
> Если миграций нету - пожалуйста добавьте их, 

Мне бы не хотелось этот модуль завязывать на миграции, потому что это затруднит поддержку старых версий django (придётся делать миграции как для django 1.7+, так и south-миграции для более ранних версий). Это усложнит год без особой на то необходимости: не думаю, что модели вообще когда-нибудь изменятся.

Именно поэтому я и хочу оставить работу с миграциями на совести пользователя. 

Насколько я понял, Вы делаете новый проект, соответственно, версия django у Вас достаточно свежая. В предыдущем комментарии я дал ссылку на документацию, где описывается настройка миграций (а именно — `MIGRATION_MODULES`. Это словарь, указывающий, в каком пакете искать миграции для того или иного приложения). 

Когда пропишете, запустите `./manage.py makemigrations`. Миграции создадутся в указанном пакете и будут использоваться точно так же, как если бы лежали в приложении.

**Comment by mcd-php** [comment]
Спасибо, получилось !

В основном проекте `settings.py`:
```python
MIGRATION_MODULES = {
    'django_ulogin': 'django_ulogin.migrations',
}
```
Затем команды в папке проекта, где `manage.py`:
```sh
source ../bin/activate
./manage.py makemigrations django_ulogin
./manage.py migrate
```
Пожалуйста, включите этот момент в документацию - поставлять пакет который при подключении ломает проект это **очень** неправильно. Всегда следует рассчитывать на новичка-энтузиаста, а не на эксперта. А если бы на моём месте был человек который не знает про GitHub и про то как обратиться к автору ?

Что касается разных версий django - можно попробовать создать скрипты исполняемые после установки, например [SO1](http://stackoverflow.com/q/20288711/1046885), [SO2](http://stackoverflow.com/q/17806485/1046885)

**Comment by marazmiki** [comment]
> Спасибо, получилось !

Пожалуйста, но не за что: Ваше решение неправильно. Миграции-то создались, но не там где нужно. А именно: не внутри вашего проекта, а непосредственно в виртуальном окружении, в `lib/python3.4/site-packages/django-ulogin/migrations`. Поэтому как только Вы склонируете свой проект в другом месте, возникнет ровно та же самая ситуация. Указывать нужно пакет **в своём проекте**. Чтобы миграции находились под версионным контролем. Что-то типа такого:

```python
    MIGRATION_MODULES = {
        'django_ulogin': 'my_project.ext_migrations.django_ulogin.migrations',
    }
```

Как вариант, можно вместо имени пакета написать None. Это выключит миграции для проекта.

> Пожалуйста, включите этот момент в документацию - поставлять пакет который при подключении ломает проект это очень неправильно.

Я не буду включать это в документацию, и вот почему.

Обратите внимание на зелёные бейджики в README, где написано "Passed". Это — результат автоматизированной сборки с прогоном тестов каждого коммита, которую любезно обеспечивает система [Travis CI](http://travis-ci.org). При сборке устанавливается Django, к проекту подключается django-ulogin, запускаются тесты. С миграциями. И вроде бы всё проходит, [можете полюбопытствовать](https://travis-ci.org/marazmiki/django-ulogin/jobs/69647625#L328).

Почему у Вас всё ломается — я, честно говоря, не знаю. Никогда не сталкивался, да и жалоб не поступало (судя по странице на pypi, django-ulogin устанавливают, и неплохо). Если есть желание, можете прислать свои исходники, я из чисто академического интереса попробую запустить их на чистом окружении. Если действительно имеет место быть ошибка, приводящая к такому результату, то исправлюсь и напишу. А пока я склонен думать, что это сайд-эффект проекта и частный случай.

> А если бы на моём месте был человек который не знает про GitHub и про то как обратиться к автору ?

Было бы замечательно, что меня не отвлекли по пустякам :-)

> Что касается разных версий django - можно попробовать создать скрипты исполняемые после установки, например SO1, SO2

Спасибо. Travis предоставляет возможность выполнять различный код в зависимости от окружения. Я просто не считаю нужным внедрять поддержку миграций в это приложение.
